ci: update build image (#2261)
To a version that is compatible with bazel 6.x pre-releases.

This isn't updating the images to the latest version due to some errors about failing to run docker from within a docker container:

```
java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unable to start docker container 'docker://envoyproxy/envoy-build-ubuntu@sha256:0adf2b7fe8763e971cfb8c2cb8e5792679b6ba194ae1fcfb1f2d8168ac03158b' on worker 'i-0379407212bdae586 (/10.1.0.80:8081)'. Maybe the requested image is not available on the worker or the local docker installation is corrupt. If the same worker fails so repeatedly, try re-creating or disabling the worker. See the documentation for more information. Error message from Docker:
'docker run sha256:8d291a1640ad581527720453fd9544acbc8069b7bf9df9ff0ea13cd8e1486dfd' (from URL 'docker://envoyproxy/envoy-build-ubuntu@sha256:0adf2b7fe8763e971cfb8c2cb8e5792679b6ba194ae1fcfb1f2d8168ac03158b') failed with [FATAL tini (6)] exec cat failed: Exec format error
```

Signed-off-by: JP Simard <jp@jpsim.com>